from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Union, Any


class BaseSchema(BaseModel):
    model_config = ConfigDict(extra="forbid")


class Function(BaseSchema):
    """Function definition for tools"""
    name: str = Field(..., description="The name of the function to be called")
    description: Optional[str] = Field(None, description="A description of what the function does")
    parameters: Optional[Dict[str, Any]] = Field(None, description="The parameters the functions accepts, described as a JSON Schema object")


class Tool(BaseSchema):
    """Tool definition for function calling"""
    type: str = Field(..., description="The type of the tool. Currently, only 'function' is supported")
    function: Function = Field(..., description="The function definition")


class ToolChoice(BaseSchema):
    """Tool choice specification"""
    type: str = Field(..., description="The type of the tool. Currently, only 'function' is supported")
    function: Dict[str, str] = Field(..., description="The function to call")


class ToolCall(BaseSchema):
    """Tool call in a message"""
    id: str = Field(..., description="The ID of the tool call")
    type: str = Field(..., description="The type of the tool call. Currently, only 'function' is supported")
    function: Dict[str, Any] = Field(..., description="The function that the model called")


class Message(BaseSchema):
    role: str = Field(..., description="The role of the message author (system, user, assistant)")
    content: Optional[str] = Field(None, description="The content of the message")
    name: Optional[str] = Field(None, description="The name of the author of this message")
    tool_calls: Optional[List[ToolCall]] = Field(None, description="The tool calls generated by the model")


class ChatCompletionRequest(BaseSchema):
    model: str = Field(..., description="ID of the model to use")
    messages: List[Message] = Field([], description="A list of messages comprising the conversation so far")
    max_tokens: Optional[int] = Field(1024, description="The maximum number of tokens to generate")
    temperature: Optional[float] = Field(1.0, description="Sampling temperature between 0 and 2")
    top_p: Optional[float] = Field(1.0, description="Nucleus sampling parameter")
    n: Optional[int] = Field(1, description="Number of chat completion choices to generate")
    stream: Optional[bool] = Field(False, description="Whether to stream back partial progress")
    stop: Optional[Union[str, List[str]]] = Field(None, description="Up to 4 sequences where the API will stop generating")
    presence_penalty: Optional[float] = Field(0.0, description="Presence penalty between -2.0 and 2.0")
    frequency_penalty: Optional[float] = Field(0.0, description="Frequency penalty between -2.0 and 2.0")
    logit_bias: Optional[Dict[str, float]] = Field(None, description="Modify the likelihood of specified tokens")
    user: Optional[str] = Field(None, description="A unique identifier representing your end-user")
    tools: Optional[List[Tool]] = Field(None, description="A list of tools the model may call")
    tool_choice: Optional[Union[str, ToolChoice]] = Field(None, description="Controls which tool is called by the model")


class Choice(BaseSchema):
    index: int
    message: Message
    finish_reason: Optional[str] = Field(None, description="The reason the model stopped generating tokens (stop, length, tool_calls, content_filter)")


class Usage(BaseSchema):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class ChatCompletionResponse(BaseSchema):
    id: str = Field(..., description="A unique identifier for the chat completion")
    object: str = Field("chat.completion", description="The object type")
    created: int = Field(..., description="The Unix timestamp when the chat completion was created")
    model: str = Field(..., description="The model used for the chat completion")
    choices: List[Choice]
    usage: Usage
    system_fingerprint: Optional[str] = Field(None, description="System fingerprint")


class ModelInfo(BaseSchema):
    id: str
    object: str = "model"
    created: int
    owned_by: str = "mobius"


class ModelsResponse(BaseSchema):
    object: str = "list"
    data: List[ModelInfo]
