name: Mobius Caller Workflow
on:
  push:
    branches: [ dev, prod, master, release ]
jobs:
  dev_job:
    if: github.ref == 'refs/heads/dev'
    uses: gaiangroup/access/.github/workflows/python-mobius-graph-operations-dev.yaml@dev
    with:
      SERVICE_CODE: mobius-llm-gateway
    secrets: inherit
  prod_job:
    if: github.ref == 'refs/heads/prod'
    uses: gaiangroup/access/.github/workflows/python-mobius-graph-operations-prod.yaml@dev
    with:
      SERVICE_CODE: mobius-llm-gateway
    secrets: inherit
  master_job:
    if: github.ref == 'refs/heads/master'
    uses: gaiangroup/access/.github/workflows/python-mobius-graph-operations-master.yaml@dev
    with:
      SERVICE_CODE: mobius-llm-gateway
    secrets: inherit
  release_job:
    if: github.ref == 'refs/heads/release'
    uses: gaiangroup/access/.github/workflows/python-mobius-graph-operations-release.yaml@dev
    with:
      SERVICE_CODE: mobius-llm-gateway
    secrets: inherit
  unauthorized_branch_job:
    if: github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/prod' && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: This is not an authorized branch, please Run on DEV or Prod Branch
        run: echo "This is not an authorized branch. please Run on DEV or Prod Branch"
